/**
 * ASP Encoder — Generates Answer Set Programming encodings
 * for ASPARTIX/clingo solvers
 * 
 * Translates the JavaScript argumentation framework into ASP facts
 * compatible with ASPARTIX-V19 (Egly, Gaggl, Woltran 2008) and
 * ICCMA benchmark format.
 * 
 * @module engine/asp-encoder
 */

/**
 * Encode an argumentation framework as ASP facts
 * Compatible with ASPARTIX and clingo
 * 
 * @param {string[]} args - Argument identifiers
 * @param {Array<[string, string]>} attacks - Attack relations
 * @returns {string} ASP encoding
 */
export function encodeAsASP(args, attacks) {
  const lines = [
    `% OAAI Framework — ASP Encoding`,
    `% Generated by Devudaaa Research Lab`,
    `% Compatible with ASPARTIX-V19 and clingo`,
    `%`,
    `% Arguments: ${args.length}`,
    `% Attacks: ${attacks.length}`,
    ``,
    `% --- Argument declarations ---`,
    ...args.map(a => `arg(${a}).`),
    ``,
    `% --- Attack relations ---`,
    ...attacks
      .filter(([a, t]) => args.includes(a) && args.includes(t))
      .map(([a, t]) => `att(${a},${t}).`),
    ``,
  ];

  return lines.join('\n');
}

/**
 * Generate grounded extension computation rules
 * @returns {string} ASP rules for grounded semantics
 */
export function groundedRules() {
  return `
% --- Grounded Extension Computation ---
% An argument is defended if all its attackers are attacked by defended arguments
% The grounded extension is the least fixed point

defeated(X) :- in(Y), att(Y,X), arg(X), arg(Y).
not_defended(X) :- att(Y,X), not defeated(Y), arg(X), arg(Y).
in(X) :- arg(X), not not_defended(X), not defeated(X).

#show in/1.
`.trim();
}

/**
 * Generate preferred extension computation rules
 * @returns {string} ASP rules for preferred semantics
 */
export function preferredRules() {
  return `
% --- Preferred Extension Computation ---
% Guess a set, verify admissibility, maximize

{in(X)} :- arg(X).

% Conflict-free check
:- in(X), in(Y), att(X,Y).

% Admissibility: every argument in the set must be defended
attacked(X,Y) :- in(X), att(Y,X), arg(Y).
defended(X) :- attacked(X,Y), in(Z), att(Z,Y).
:- in(X), attacked(X,_), not defended(X).

% Maximize (preferred = maximal admissible)
#maximize { 1,X : in(X) }.

#show in/1.
`.trim();
}

/**
 * Generate stable extension computation rules
 * @returns {string} ASP rules for stable semantics
 */
export function stableRules() {
  return `
% --- Stable Extension Computation ---
% Conflict-free + attacks all outsiders

{in(X)} :- arg(X).

% Conflict-free
:- in(X), in(Y), att(X,Y).

% Every argument not in must be attacked by something in
:- arg(X), not in(X), not defeated(X).
defeated(X) :- in(Y), att(Y,X).

#show in/1.
`.trim();
}

/**
 * Generate complete encoding (facts + rules) for a specific semantics
 * 
 * @param {string[]} args
 * @param {Array<[string, string]>} attacks
 * @param {'grounded'|'preferred'|'stable'} semantics
 * @returns {string}
 */
export function generateFullEncoding(args, attacks, semantics = 'grounded') {
  const facts = encodeAsASP(args, attacks);
  
  const ruleGenerators = {
    grounded: groundedRules,
    preferred: preferredRules,
    stable: stableRules,
  };

  const rules = (ruleGenerators[semantics] || groundedRules)();

  return `${facts}\n${rules}\n`;
}

/**
 * Generate ICCMA competition format (.apx file)
 * 
 * @param {string[]} args
 * @param {Array<[string, string]>} attacks
 * @returns {string} ICCMA .apx format
 */
export function encodeAsICCMA(args, attacks) {
  const lines = [
    ...args.map(a => `arg(${a}).`),
    ...attacks
      .filter(([a, t]) => args.includes(a) && args.includes(t))
      .map(([a, t]) => `att(${a},${t}).`),
  ];
  return lines.join('\n');
}
